In [4]:
import pandas as pd

In [5]:
person = {
    "first": 'Ademola',
    "last": "Akinwale",
    "email": "Ademola_akinwale@yahoo.com"
}

In [6]:
person_2 = {
    "first": ["Qudus"],
    "last": ["Abiodun"],
    "email": ["Qdubs10@gmail.com"]
}

In [7]:
people = {
    "first": ["Ademola", "Qudus", "Muneerah"],
    "last": ["Akinwale", "Abiodun", "Lawal"],
    "email": ["Ademola_akinwale@yahoo.com", "Qdubs10@gmail.com", "Mlawal01@gmail.com"]
}

In [15]:
df = pd.DataFrame(people)

In [14]:
df

      first      last                       email
0   Ademola  Akinwale  Ademola_akinwale@yahoo.com
1     Qudus   Abiodun           Qdubs10@gmail.com
2  Muneerah     Lawal          Mlawal01@gmail.com

In [13]:
df.set_index('email') #This will set the index to email, instead of it starting from "first", it will now be 
                            #starting from the email

                               first      last
email
Ademola_akinwale@yahoo.com   Ademola  Akinwale
Qdubs10@gmail.com              Qudus   Abiodun
Mlawal01@gmail.com          Muneerah     Lawal

In [16]:
df.set_index('email', inplace = True)

In [17]:
df

                               first      last
email
Ademola_akinwale@yahoo.com   Ademola  Akinwale
Qdubs10@gmail.com              Qudus   Abiodun
Mlawal01@gmail.com          Muneerah     Lawal

In [18]:
df.index

Index(['Ademola_akinwale@yahoo.com', 'Qdubs10@gmail.com',
       'Mlawal01@gmail.com'],
      dtype='object', name='email')

In [19]:
df.loc['Ademola_akinwale@yahoo.com'] #Do this to retrieve information about the email

first     Ademola
last     Akinwale
Name: Ademola_akinwale@yahoo.com, dtype: object

In [20]:
df.loc["Ademola_akinwale@yahoo.com", "last"] #This will retreive the last name

'Akinwale'

In [22]:
df.reset_index("email", inplace = True) # To reset the index

In [23]:
df

                        email     first      last
0  Ademola_akinwale@yahoo.com   Ademola  Akinwale
1           Qdubs10@gmail.com     Qudus   Abiodun
2          Mlawal01@gmail.com  Muneerah     Lawal

In [24]:
import pandas as pd

In [25]:
df_1 = pd.read_csv('data/survey_results_public.csv') #we can set the index here by passing in the arguments before
#closing the the parenthesis i.e df_1 = pd.read_csv('data/survey_results_public.csv', index_col = "Respondent")
#And it can also be done after reading in the file like i did below

In [26]:
df_1.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [27]:
df_1.set_index("Respondent")

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [28]:
df_1.loc[1] #To generate the first respondent

Respondent                                                      2
MainBranch                 I am a student who is learning to code
Hobbyist                                                       No
OpenSourcer                               Less than once per year
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 1, Length: 85, dtype: object

In [43]:
import pandas as pd

In [44]:
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [46]:
schema_df

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [48]:
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col = "Column")

In [49]:
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [50]:
schema_df.loc['Hobbyist']

QuestionText    Do you code as a hobby?
Name: Hobbyist, dtype: object

In [51]:
schema_df.loc["MgrIdiot"] #By default, the QuestionText is truncated by to revealed the full text then we can pass
                          #in column name as shown below

QuestionText    How confident are you that your manager knows ...
Name: MgrIdiot, dtype: object

In [53]:
schema_df.loc["MgrIdiot", "QuestionText"] # Here the full text is shown

'How confident are you that your manager knows what they’re doing?'

In [54]:
schema_df.sort_index() # This will sort the index in alphabetical order and to sort permernently then we will have
                        #to pass in an 'inplace' and set it to true

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]

In [56]:
schema_df.sort_index(ascending = False) #To sort index in descending order

                                                    QuestionText
Column
YearsCodePro   How many years have you coded professionally (...
YearsCode      Including any education, how many years have y...
WorkWeekHrs     On average, how many hours per week do you work?
WorkRemote                       How often do you work remotely?
WorkPlan                 How structured or planned is your work?
...                                                          ...
BlockchainOrg  How is your organization thinking about or imp...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BetterLife     Do you think people born today will have a bet...
Age1stCode     At what age did you write your first line of c...
Age            What is your age (in years)? If you prefer not...

[85 rows x 1 columns]

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [52]:
schema_df.iloc[10]

QuestionText    Which of the following types of non-degree edu...
Name: EduOther, dtype: object